[package]
name = "anvfication"
version = "0.1.0"
edition = "2021"
authors = ["anubhavg@infopercept.com"]

[[bin]]
name = "gitgraph"
path = "src/gitgraph.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.3"
